<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Entries;

class BoardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $boards=[

            ['Nabil Qaddumi', 'نبيل قدومي', 'Acting Chairperson', ' رئيس مجلس الأمناء بالوكالة', '                                                                                                                                                                                                                        <p>Dr. Nabil Qaddumi is the founder and Chairman of SPETCO International Petroleum\r\nCompany (SPETCO) and the Chairman of United Materials Company (MAWAD).\r\nHe is also the founder and previous Chairman of PROJACS International,\r\na leading regional project management company. Dr. Qaddumi sits on the Board of Directors of the Jordan Investment & Finance Bank (INVESTBANK). In the public service domain, he was the Chairman of the Board of Trustees of the Welfare Association (TAAWON), and is the Director of the Hani Qaddumi\r\nScholarship Foundation (HQSF), the Vice Chairman of the Arab Fund for Arts &\r\nCulture (AFAC), a member of the Board of the Institute for Palestine Studies\r\n(IPS), and previous Palestine’s Governor at the Arab Fund for Economic and\r\nSocial Development.\r\nDr. Qaddumi received his education in Lebanon and the United States. He studied\r\nat the American University of Beirut and has degrees from the University of Texas,\r\nStanford University, and MIT, all in civil engineering.\r\nHe was a lecturer at Kuwait University, and a visiting lecturer at Stanford University.</p>                                                                                                                                                                                                                                                                 ', '                                    مؤسّس ورئيس مجلس إدارة شركة \"Spetco النفطية\"، رئيس مجلس إدارة \"شركة المواد المتكاملة\" ومؤسّس ورئيس مجلس إدارة سابق لشركة \"بروجاكس العالمية\"، شركة عربية رائدة في إدارة المشاريع. هو أيضاً عضو مجلس إدارة البنك الإستثماري في الأردن.  في المجال العام، كان رئيس مجلس أمناء \"مؤسسة التعاون\" وهو  مدير \"مؤسسة هاني القدومي للمنح الدراسية\"، وعضو مجلس أمناء \"مؤسسة الدراسات الفلسطينية\" ومحافظ فلسطين السابق لدى الصندوق العربي للإنماء الاقتصادي والاجتماعي.  درس في لبنان والولايات المتحدة، وحاز على شهادات في الهندسة المدنية من الجامعة الأميركية في بيروت، جامعة تكساس، جامعة ستانفورد و MIT. كان محاضراً في جامعة الكويت ومحاضراً زائراً في جامعة ستانفورد.\r\n\r\n                                                                                           '],
            ['Suzanne Wettenschwiler', 'سوزان فتنشفويللر', 'Statutory Secretary', 'السكرتيرة القانونية', '                                    <p>A member of the Swiss Bar Association, Dr. Wettenschwiler is a commercial and not-for-profit attorney based in Zug, Switzerland. Having earned a PhD from the University of Zurich Law School, she is a member of the HDV Canton of Zug (Trade and Services Association), the SRO VQF (Association of Quality Assurance in Financial Services) and the International Bar Association (IBA). Dr. Wettenschwiler is also a member of the board of the Open Society Institute Zug and various other Swiss charitable foundations.</p>                                                                                                ', '                                                                        <p>عضو نقابة المحامين السويسرية ومحامية في القطاعين التجاري وغير الربحي ومقرها مدينة زوغ في سويسرا. تحمل درجة الدكتوراه في القانون من جامعة زوريخ وهي عضو في مؤسسة التجارة والخدمات بمدينة زوغ ومؤسسة ضمان الجودة في الخدمات المالية ورابطة المحامين الدولية. كما أنها عضو في مجلس مؤسسة \"أوبن سوساييتي\" بمدينة زوغ وغيرها من المؤسسات الخيرية السويسرية.<br></p>                                                                '],
            ['Amr Ben Halim', 'عمرو بن حليم', '', '', '                                    <p>Amr has served and partnered with multinational engineering and project management firms in developing, building and operating industrial projects.\r\n</p><p>\r\nHe is a founder, board member and  shareholder of  companies that are leading providers of hydrocarbon processing, energy, and industrial services in the Kingdom of Saudi Arabia .\r\n</p><p>\r\nHe founded one of the first women-led micro-lending programs in the refugee camps of south Lebanon. In addition , through a family trust, he has founded the first NGO exclusively dedicated to supporting mental health and well-being projects in the Arab World.\r\n</p><p>\r\nHe is also a founder board member of the Forum for Democratic Libya, an NGO working to promote transparency, civic engagement, and arts and culture in Libya. He continues to be an active member and supporter of various philanthropic and civil society projects in the Arab world.\r\n</p><p>\r\nAmr also recently served as the Executive producer of ‘First to Fall’, the first full-length documentary on the Libyan revolution.\r\n</p><p>\r\nHe has degrees from Stanford University with an MBA and MS in civil engineering  and a BSc from the University of Wales                                                                                                                                                                </p>                                ', '                                                                                                                                                <p>عمرو شريك وناشط في شركات هندسة ومقاولات متعدّدة الجنسيات ناشطة في مجال تطوير وبناء وتشغيل المشاريع الصناعية.</p><p> هو مؤسّس ومساهم وعضو مجلس إدارة شركات رائدة في مجال تحويل الهايدروكاربون وخدمات الطاقة والخدمات الصناعية في المملكة العربية السعودية.</p><p> أسس أحد أوائل برامج القروض الصغيرة المدارة من قبل نساء في مخيمات اللاجئين في جنوب لبنان، كما أسس، من خلال صندوق عائلي، أول مؤسسة غير حكومية تعنى حصراً بدعم مشاريع الصحة الذهنية والنفسية في العالم العربي.</p><p> بالإضافة لكونه مؤسّس وعضو مجلس أمناء منتدى ليبيا الديمقراطية وهي منظمة غير حكومية عاملة في مجال نشر ثقافة الشفافية والمشاركة المدنية والديمقراطية في ليبيا، يتابع بن حليم نشاطه كعضو فاعل وداعم للكثير من المشاريع الخيرية والمدنية في العالم العربي.</p><p>عمل عمرو مؤخراً كمنتج منفّذ لأول فيلم وثائقي طويل عن الثورة الليبية تحت عنوان \"أول من سقط\".</p><p>يحمل عمرو شهادات ماجستير في إدارة الأعمال والهندسة المدنية  من جامعة ستانفورد بالإضافة الى شهادة بكالوريوس العلوم من جامعة ويلز.</p>                                                                                                                                                                                                    '],
            ['Roxane Zand', 'روكسان زند', '', '', '                                    <p>Harvard and Oxford educated, Roxane Zand began a career in museum and arts administration after three years in UNESCO. She left Iran after the Revolution to resume professional activities in London in the field of education and the arts, and was one of the founding members of the Harvard Club of London. Mrs Zand moved to Asia House in 1999, and also worked as a freelance consultant for numerous projects for the British Museum and elsewhere in the art world before joining Sotheby’s in 2006, where she is now Deputy Chairman for the Middle East. Currently she sits on the Advisory Council of the Pictet Art Prize, the Development Board of the University of the Arts London, and has been appointed as a Deputy Lieutenant for Greater London for her services to Middle Eastern art and culture. She is also arts editor for the Encyclopedia Islamica. At Sotheby’s she has played an instrumental role in developing and contributing to sales of Arab and Iranian art, and has conducted a number of charity auctions to benefit causes in the MENA region.</p>                                                                                                                                    ', '                                    <p>خريجة جامعتي هارفارد وأوكسفورد، بدأت مهنتها في إدارة المتاحف والفنون بعد ثلاث سنوات من العمل في اليونيسكو. غادرت إيران بعد الثورة لمتابعة نشاطها المهني في لندن في مجال التعليم والفن، وكانت من الأعضاء المؤسسين لنادي هارفارد في لندن. انتقلت الى بيت آسيا في العام 1999، وعملت كمستشارة مستقلّة في عدد من المشاريع التابعة للمتحف البريطاني، ولغيره من المؤسسات المعنية بالفن قبل أن تنضم الى \"سوثيبي\" في العام 2006، حيث تشغل منصب نائب رئيس مجلس ادارة لمنطقة الشرق الأوسط. هي حالياً عضو المجلس الاستشاري لجائزة \"بيكتيه\" للفن، ولهيئة التنمية في جامعة الفنون في لندن، كما كان قد تم تعيينها نائب ملازم أول للندن الكبرى لقاء خدماتها تجاه الفن والثقافة في الشرق الأوسط. هي أيضا محرّرة للفنون في موسوعة \"اسلاميكا\". لعبت دوراً محوريا في سوثيبي لناحية تطويرها ومساهمتها في مبيع الفن العربي والايراني، كما نظّمت عدداً من المزادات الخيرية لصالح قضايا في منطقة الشرق الأوسط وشمال أفريقيا.\r\n</p>                                '],
            ['Oussama Rifahi', 'أسامة الرفاعي', '', '', '                                                                                                            <p>Oussama is a cultural management consultant and museum development expert based in Cologne and Beirut. Oussama advises cultural organizations in business development and philanthropy and provides consultancy services to foundations, private corporations and governmental bodies on national cultural strategies and governance. Oussama is involved in the design and implementation of various artistic and cultural programs and museum development projects in Europe, the MENA region and Africa. He is a board member of the Arab Fund for Arts and Culture and is supporting the development of similar regional cultural funds internationally.</p>                                                                                                                                              ', '                                                                        أسامة الرفاعي مستشار في الإدارة الثقافية وخبير في تطوير المتاحف، مقيم بين كولون في ألمانيا وبيروت. يعمل مع المنظمات الثقافية بصفة مستشار في مجال تطوير الأعمال والمبادرات الفيلانثروبية، كما يقدّم خدمات استشارية للمؤسسات والشركات الخاصة والهيئات الحكومية حول الاستراتيجيات الثقافية الوطنية والحوكمة. شارك أسامة في تصميم وتنفيذ العديد من البرامج الفنية والثقافية ومشاريع تطوير المتاحف في أوروبا ومنطقة الشرق الأوسط وشمال إفريقيا وأفريقيا. هو عضو في مجلس أمناء الصندوق العربي للثقافة والفنون - آفاق ويدعم تطوير صناديق ثقافية إقليمية مماثلة على المستوى الدولي.                                                                                                '],
            ['Hani Kalouti', 'هاني كالوتي', '', '', '                                                                        <p>Hani Kalouti, is the President and Founder of HBK Investments Advisory S.A. based in Geneva, Switzerland. HBK is a multi-family asset management firm providing independent expert advice to high net worth individuals, their families and foundations. Mr. Kalouti started his career with Citibank, New York in 1981 and was chief investment officer of their Swiss Private Bank in Geneva when he left in 1996 to establish HBK. He holds a B. S. degree in Civil Engineering from the University of Wisconsin-Madison and an MBA from Syracuse University, New York. He is a member of the Board of Trustees and Management Committee of the Welfare Association.</p>                                                                           ', '                                    رئيس ومؤسّس HBK للاستشارات الاستثمارية ومقرها جنيف - سويسرا التي تقدّم الخبرات المعتمدة والموثوقة للاستثمارات الشخصية والعائلية وللمؤسسات. بدأ كالوتي حياته العملية مع \"سيتي بنك\" (Citibank) في نيويورك عام 1981 حيث كان مسؤولاً رئيساً عن الاستثمارات الخاصة بالبنك في جنيف حتى عام 1996، ليؤسس بعد ذلك HBK. كما يحمل درجة البكالوريوس في الهندسة المدنية من جامعة ويسكونسن - ماديسون، ودرجة الماجستير في مجال إدارة الاعمال من جامعة سيراكيوز في نيويورك. وهو عضو  مجلس أمناء ولجنة إدارة \"مؤسسة التعاون\".                                '],
            ['Mona Khazindar', 'منى خزندار', '', '', '<div>Curator and historian Mona Khazindar has curated numerous international exhibitions for the past 30 years. She was the first female (and first Saudi) Director of the Arab World Institute of Paris, a position that she held from 2011 to 2014.&nbsp;</div><div><br></div><div>In 2012, Khazindar was appointed a permanent member of the board of trustees of the Museum of the Civilizations of Europe and the Mediterranean (MUCEM) by the French Minister of Culture. In 2014–2015, she was appointed cultural advisor to the President of the Saudi Commission for Tourism and Antiquities (SCTA). And in 2018, Khazindar was appointed by Royal decree, as member of the Saudi Cultural Authority and nominated as member of the Ithra advisory council.&nbsp;</div><div><br></div><div>In 2017, Khazindar founded Palette, an arts and culture collective that engineers cultural projects and art publications. Khazindar has written widely in Arab and European publications on Arab art, culture and history.&nbsp; She has authored the book Visions from Abroad, Historical and Contemporary Representations of Saudi Arabia.</div><div><br></div><div>A Saudi national, Khazindar holds a postgraduate degree (DEA) in Contemporary and Modern History from the Sorbonne and a bachelor’s degree in Comparative Literature from the American University in Paris.&nbsp;</div>                                                                    ', '<div>أشرفت القيّمة والمؤرّخة الفنية منى خزندار على عدّة معارض دولية خلال السنوات الثلاثين الماضية. شغلت منصب المديرة العامة لمعهد العالم العربي في باريس من 2011 الى 2014 لتكون المرأة الأولى التي تشغل هذا المنصب.&nbsp;</div><div><br></div><div>في العام 2012، عيّنت وزارة الثقافة الفرنسية خزندار عضوة دائمة في مجلس أمناء متحف حضارات أوروبا والمتوسّط. في 2014 و2015 عملت كمستشارة لرئيس الهيئة العامة للسياحة والآثار في السعودية. وفي 2018 تم تعيينها بمرسوم ملكي كعضوة في هيئة الثقافة السعودية ورشّحت للمجلس الإستشاري لمركز الملك عبد العزيز الثقافي العالمي - إثراء.</div><div><br></div><div>أسست في العام 2017 مجموعة الفنون والثقافة \"باليت\" التي تعمل في مجال هندسة المشاريع الثقافية والمنشورات الفنية. لخزندار مشاركات كثيرة في منشورات عربية وأوروبية عدّة حول الفن والثقافة والتاريخ العربي. ألفت كتاب \"رؤى من الخارج: طروحات تاريخية ومعاصرة للمملكة العربية السعودية\".</div><div><br></div><div>تحمل خزندار شهادة عليا في التاريخ المعاصر والحديث من جامعة السوربون وشهادة بكالوريوس في الأدب المقارن من الجامعة الأميركية في باريس.</div>                                                                    '],
            ['Rania Kuzbari Ashur', 'رانيا كزبري عاشور ', '', '', '<div>Rania Kuzbari Ashur is the founder and CEO of “Art for All”, the Middle East region’s leading provider of live theatre and educational stage shows for children of all ages, envisioned as a way to fill the ‘artistic and cultural’ void for children living in Dubai.</div><div><br></div><div>She brought The Shakespeare Globe and the English National Ballet for the first time to the UAE, and introduced the concept of workshops to educate children about art and the theatre.</div><div><br></div><div>“Art for All” held over 40 productions touring the UAE, presenting shows and delivering</div><div>specialized workshops, reaching an audience of 100,000 children.</div><div><br></div><div>Ashur holds a BA and Masters in Political Sciences from the American University of Beirut, and a DEA (Diplome d’études Approfondies) in International Relations from the Paris Institute of Political Sciences.</div>                                                                    ', '<div>رانيا كزبري عاشور هي مؤسِّسة ورئيسة مجلس إدارة \"الفن للجميع\" التي تعتبر في طليعة مبرمجي العرو ض المسرحية الحيّة والعروض المسرحية التربوية للأطفال من مختلف الأعمار في منطقة الشرق الأوسط. تهدف \"الفن للجميع\" الى سدّ الثغرة \"الفنية والثقافية\" للأطفال في دبي.</div><div><br></div><div>هي أول من جلب \"شاكسبير غلوب\" وفرقة الباليه الوطنية الإنكليزية الى الإمارات العربية المتحّدة كما كانت أول من أطلق ورشات العمل لتعليم الأطفال عن الفن والمسرح في المنطقة.</div><div><br></div><div>نظّمت \"الفن للجميع\" أكثر من 40 عرضاً جوالاً في الإمارات العربية المتّحدة بالإضافة الى العديد من العروض وورش العمل المتخصّصة التي شارك فيها أكثر من 100 ألف طفل.</div><div>تحمل عاشور شهادتي البكالوريوس والماجستير في العلوم السياسية من الجامعة الأميركية في بيروت وشهادة عليا في العلاقات الدولية من معهد باريس للعلوم السياسية.</div>                                                                    '],


        ];

        foreach ($boards as $board) {
            Entries::updateOrCreate([
                'type_id'=>'10',
                'board_name' => $board[0],
                'board_name_arabic' => $board[1],
                'board_position' => preg_replace('/\s+/', ' ',$board[2]),
                'board_position_arabic' => preg_replace('/\s+/', ' ',$board[3]),
                'board_text' => trim(str_replace("\\r\\n", "",$board[4])),
                'board_text_arabic' => trim(str_replace("\\r\\n", "",$board[5])),
                'published'=>'1' 
            ]);
        }

    }
}
