<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Countries;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $countries = [
            ['Lebanon', 'لبنان'],
            ['Afghanistan', 'أفغانستان'],
            ['Akrotiri', 'أكروتيري'],
            ['Albania', 'ألبانيا'],
            ['Algeria', 'الجزائر'],
            ['American Samoa', 'ساموا'],
            ['Andorra', 'أندورا'],
            ['Angola', 'أنغولا'],
            ['Anguilla', 'أنغيلا'],
            ['Antarctica', 'أنتراكتيكا'],
            ['Antigua and Barbuda', 'أنتيغوا وبربودا'],
            ['Argentina', 'الأرجنتين'],
            ['Armenia', 'أرمينيا'],
            ['Aruba', 'أروبا'],
            ['Ashmore and Cartier Islands', 'جزر أشمور وكارتييه'],
            ['Australia', 'أستراليا'],
            ['Austria', 'النمسا'],
            ['Azerbaijan', 'أذربيجان'],
            ['Bahamas', 'جزر البهاما'],
            ['Bahrain', 'البحرين'],
            ['Bangladesh', 'بنغلاديش'],
            ['Barbados', 'بربادوس'],
            ['Bassas da India', 'باساس الهندية'],
            ['Belarus', 'روسيا البيضاء'],
            ['Belgium', 'بلجيكا'],
            ['Belize', 'بيليز'],
            ['Benin', 'بنين'],
            ['Bermuda', 'برمودا'],
            ['Bhutan', 'بوتان'],
            ['Bolivia', 'بوليفيا'],
            ['Bosnia and Herzegovina', 'البوسنة والهرسك'],
            ['Botswana', 'بوتسوانا'],
            ['Bouvet Island', 'جزر بوفي'],
            ['Brazil', 'البرازيل'],
            ['British Indian Ocean Territory', 'الأراضي البريطانية في المحيط الهندي'],
            ['British Virgin Islands', 'جزر العذراء البريطانية'],
            ['Brunei', 'بروني'],
            ['Bulgaria', 'بلغاريا'],
            ['Burkina Faso', 'بوركينا فاسو'],
            ['Burma', 'بورما'],
            ['Burundi', 'بوروندي'],
            ['Cambodia', 'كمبوديا'],
            ['Cameroon', 'الكاميرون'],
            ['Canada', 'كندا'],
            ['Cape Verde', 'الرأس الأخضر'],
            ['Cayman Islands', 'جزر كايمان'],
            ['Central African Republic', 'جمهورية أفريقيا الوسطى'],
            ['Chad', 'تشاد'],
            ['Chile', 'شيلي'],
            ['China', 'الصين'],
            ['Christmas Island', 'جزيرة كريسماس'],
            ['Clipperton Island', 'جزيرة كليبرتون'],
            ['Cocos (Keeling) Islands', 'جزر كوكوس'],
            ['Colombia', 'كولومبيا'],
            ['Comoros', 'جزر القمر'],
            ['Democratic Republic of the Congo', 'جمهورية الكونغو الديمقراطية'],
            ['Republic of the Congo', 'جمهورية الكونغو'],
            ['Cook Islands', 'جزر كوك'],
            ['Coral Sea Islands', 'جزر كورال سي'],
            ['Costa Rica', 'كوستاريكا'],
            ['Cote d\'Ivoire', 'ساحل العاج'],
            ['Croatia', 'كرواتيا'],
            ['Cuba', 'كوبا'],
            ['Cyprus', 'قبرص'],
            ['Czech Republic', 'الجمهورية التشيكية'],
            ['Denmark', 'الدانمارك'],
            ['Djibouti', 'جيبوتي'],
            ['Dominica', 'دومينيكا'],
            ['Dominican Republic', 'الجمهورية الدومينيكية'],
            ['Ecuador', 'اكوادور'],
            ['Egypt', 'مصر'],
            ['El Salvador', 'السلفادور'],
            ['Equatorial Guinea', 'غينيا الاستوائية'],
            ['Eritrea', 'اريتريا'],
            ['Estonia', 'استونيا'],
            ['Ethiopia', 'اثيوبيا'],
            ['Europa Island', 'جزيرة أوروبا'],
            ['Falkland Islands', 'جرز الفولكلاند'],
            ['Faroe Islands', 'جزر فارو'],
            ['Fiji', 'فيجي'],
            ['Finland', 'فنلندا'],
            ['France', 'فرنسا'],
            ['French Guiana', 'غيانا الفرنسية '],
            ['French Polynesia', 'بولينزيا الفرنسية'],
            ['French Southern and Antarctic Lands', 'لأراضي الفرنسية في المحيط الجنوبي وأنتاركتيكا '],
            ['Gabon', 'غابون'],
            ['Gambia', 'غامبيا'],
            ['Georgia', 'جورجيا'],
            ['Germany', 'المانيا'],
            ['Ghana', 'غانا'],
            ['Gibraltar', 'جبل طارق'],
            ['Glorioso Islands', 'جزر جلوريوسو'],
            ['Greece', 'اليونان'],
            ['Greenland', ' غرينلاند'],
            ['Grenada', 'غرينادا'],
            ['Guadeloupe', 'غواديلوب'],
            ['Guam', 'غوام'],
            ['Guatemala', 'غواتيمالا'],
            ['Guernsey', 'غيرنسي'],
            ['Guinea', 'غينيا'],
            ['Guinea-Bissau', 'غينيا - بيساو'],
            ['Guyana', 'غيانا '],
            ['Haiti', 'هايتي'],
            ['Heard Island and McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد'],
            ['Holy See ', 'الكرسي الرسولي'],
            ['Honduras', 'هندوراس'],
            ['Hong Kong', 'هونغ كونغ'],
            ['Hungary', 'هنغاريا'],
            ['Iceland', 'أيسلندا'],
            ['India', 'الهند'],
            ['Indonesia', 'اندونسيا'],
            ['Iran', 'إيران'],
            ['Iraq', 'العراق'],
            ['Ireland', 'ايرلندا'],
            ['Isle of Man', 'جزيرة مان'],
            ['Italy', 'ايطاليا'],
            ['Jamaica', 'جامايكا'],
            ['Jan Mayen', 'جان ماين'],
            ['Japan', 'اليابان'],
            ['Jersey', 'جيرزي'],
            ['Jordan', 'الأردن'],
            ['Juan de Nova Island', 'جوان دي نوفا'],
            ['Kazakhstan', 'كازاخستان'],
            ['Kenya', 'كينيا'],
            ['Kiribati', 'كيريباتي'],
            ['North Korea', 'كوريا الشمالية'],
            ['South Korea', 'كوريا الجنوبية'],
            ['Kuwait', 'الكويت'],
            ['Kyrgyzstan', 'قيرغيزستان'],
            ['Laos', 'لاوس'],
            ['Latvia', 'لاتفيا'],
            ['Liberia', 'ليبيريا'],
            ['Liechtenstein', 'ليختنشتاين'],
            ['Lithuania', 'ليتوانيا'],
            ['Luxembourg', 'لكسمبرغ'],
            ['Macau', 'ماكاو'],
            ['Macedonia', 'مقدونيا'],
            ['Madagascar', 'مدغشقر'],
            ['Malawi', 'ملاوي'],
            ['Malaysia', 'ماليزيا'],
            ['Maldives', 'ملديف'],
            ['Mali', 'مالي'],
            ['Malta', 'مالطة'],
            ['Marshall Islands', 'جزر مارشال'],
            ['Martinique', 'مارتينيك'],
            ['Mauritania', 'موريتانيا'],
            ['Mauritius', 'موريشيوس'],
            ['Mayotte', 'مايوت'],
            ['Mexico', 'المكسيك'],
            ['Micronesia', 'ميكرونيزيا'],
            ['Moldova', 'مولدوفا'],
            ['Monaco', 'موناكو'],
            ['Mongolia', 'منغوليا'],
            ['Montserrat', 'مونتسيرات'],
            ['Morocco', 'المغرب'],
            ['Mozambique', 'موزامبيق'],
            ['Namibia', 'ناميبيا'],
            ['Nauru', 'ناورو'],
            ['Navassa Island', 'جزيرة نافاسا'],
            ['Nepal', 'نيبال'],
            ['Netherlands', 'هولندا'],
            ['Netherlands Antilles', 'جزر الأنتيل الهولندية'],
            ['New Caledonia', 'كاليدونيا الجديدة'],
            ['New Zealand', 'نيوزيلندا'],
            ['Nicaragua', 'نيكاراغوا'],
            ['Niger', 'النيجر'],
            ['Nigeria', 'نيجيريا'],
            ['Niue', 'نيوي'],
            ['Norfolk Island', ' جزيرة نورفولك'],
            ['Northern Mariana Islands', 'جزر ماريانا الشمالية'],
            ['Norway', 'النرويج'],
            ['Oman', 'عمان'],
            ['Pakistan', 'باكستان'],
            ['Palau', 'بالاو'],
            ['Palestine', 'فلسطين'],
            ['Panama', 'بنما'],
            ['Papua New Guinea', 'بابوا غينيا الجديدة'],
            ['Paracel Islands', 'جزر باراسيل'],
            ['Paraguay', 'باراغواي'],
            ['Peru', 'بيرو'],
            ['Philippines', 'الفلبين'],
            ['Pitcairn Islands', 'جزر بيتكيرن'],
            ['Poland', 'بولندا'],
            ['Portugal', 'البرتغال'],
            ['Puerto Rico', 'بورتوريكو'],
            ['Qatar', 'قطر'],
            ['Reunion', 'ريونيون'],
            ['Romania', ' رومانيا'],
            ['Russia', 'روسيا'],
            ['Rwanda', 'رواندا'],
            ['Saint Helena', 'سانت هيلينا'],
            ['Saint Kitts and Nevis', 'سانت كيتس ونيفيس'],
            ['Saint Lucia', 'سانت لوسيا'],
            ['Saint Pierre and Miquelon', 'سان بيير وميكلون'],
            ['Saint Vincent and the Grenadines', 'سانت فينسنت وجزر غرينادين'],
            ['Samoa', 'ساموا'],
            ['San Marino', 'سان مارينو'],
            ['Sao Tome and Principe', 'سان تومي وبرينسيـبي'],
            ['Saudi Arabia', 'المملكة العربية السعودية'],
            ['Senegal', 'السنغال'],
            ['Serbia', ''],
            ['Serbia', 'صربيا'],
            ['Montenegro', 'الجبل الأسود'],
            ['Seychelles', 'سيشيل'],
            ['Sierra Leone', 'سيراليون'],
            ['Singapore', 'سنغافورة'],
            ['Slovakia', 'سلوفاكيا'],
            ['Slovenia', 'سلوفينيا'],
            ['Solomon Islands', 'جزر سليمان'],
            ['Somalia', 'الصومال'],
            ['South Africa', 'جنوب افريقيا'],
            ['South Georgia and the South Sandwich Islands', 'جزر جورجيا الجنوبية وساندويتش الجنوبية'],
            ['Spain', 'اسبانيا'],
            ['Spratly Islands', 'جزر سبراتلي'],
            ['Sri Lanka', 'سري لانكا'],
            ['Sudan', 'السودان'],
            ['Suriname', 'سورينام'],
            ['Svalbard', 'سفالبارد'],
            ['Swaziland', 'سوازيلاند'],
            ['Sweden', 'السويد'],
            ['Switzerland', 'سويسرا'],
            ['Syria', 'سوريا'],
            ['Taiwan', 'تايوان'],
            ['Tajikistan', 'طاجيكستان'],
            ['Tanzania', 'تنزانيا'],
            ['Thailand', 'تايلند'],
            ['Timor-Leste', 'تيمور-ليشتي'],
            ['Togo', 'توغو'],
            ['Tokelau', 'توكيلاو'],
            ['Tonga', 'تونغا'],
            ['Trinidad and Tobago', 'ترينيداد وتوباغو'],
            ['Tromelin Island', 'جزيرة تروملين'],
            ['Tunisia', 'تونس'],
            ['Turkey', 'تركيا'],
            ['Turkmenistan', 'تركمنستان'],
            ['Turks and Caicos Islands', 'جزر تركس وكايكوس'],
            ['Tuvalu', 'توفالو'],
            ['Uganda', 'أوغندا'],
            ['Ukraine', 'أوكرانيا'],
            ['United Arab Emirates', 'الإمارات العربية المتّحدة'],
            ['United Kingdom', 'المملكة المتّحدة'],
            ['United States', 'الولايات المتّحدة الأميركية'],
            ['Uruguay', 'أوروغواي'],
            ['Uzbekistan', 'أوزبكستان'],
            ['Vanuatu', 'فاناتو'],
            ['Venezuela', 'فنزويلا'],
            ['Vietnam', 'فيتنام'],
            ['Virgin Islands', 'الجزر العذراء'],
            ['Wake Island', 'جزيرة ويك'],
            ['Wallis and Futuna', 'واليس وفوتونا'],
            ['Western Sahara', 'الصحراء الغربية'],
            ['Yemen', 'اليمن'],
            ['Zambia', 'زامبيا'],
            ['Zimbabwe', 'زيمبابوي'],
            ['Libya', 'ليبيا'],
            
        ];


        foreach ($countries as $country) {
            Countries::updateOrCreate(['name' => $country[0],'name_arabic' => $country[1] , 'active'=>'1']);
        }
    }
}
