<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Entries;

class EventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
    */

    public function run(): void
    {
        /*$images=
        [
            'entries/qd6nO4xKbeIlQ3h4UEbZRRwF1B3ubjIALPvJIc4k.jpg',
            'entries/RqLxM6noQCBeUFQLQbq2oHFT5vs3qKQPpWHoW2rL.jpg',
            'entries/OjCWB6nuBHGGVM4IgyC6TCBpdrlQ17I1S5Hx0SfC.jpg',
            'entries/VRwhavcLy5uVmV0qAv7v4R6g8kd8uglWLegaV4Ut.jpg',
            'entries/9Fm9r5eNI9lKs8dhlyp9ce3nmJxwYm5WVs79jzxf.jpg',
            'entries/LKJF31m7tJ2PFHOxDWO1JAhYdY2XfVIJIFD3ML3J.jpg',
            'entries/6mFqY8D4DeZmny82KZwAfM2iX57SrMn9X3Wbmcwv.jpg',
        ];

        $image_featured=
        [
            'entries/ZMNc58X6hdo11lWFCSgAPUoBPvveYxNOJ9liRNS6.jpg',
            'entries/7c10thiwMvgmyzh7XGfmPYF7S8Z11sgHKhlk075P.jpg',
            'entries/CtHGHTQfRyHdka0esRnD0pdiIYjmlqI3IpuSE7ds.jpg',
            'entries/b2dkCAtP6r44y5Qh8FH6Ht34ovPazMoI2Q6GU5n0.jpg',
            'entries/VeuBojTpKIwlCY5IuXiyXKVJw2QsW2DCtbNYWwAb.jpg',
            'entries/UrUR1Zozcej8zfs2bDfHsDTs3JU4iqfAqVfQVfj8.jpg',
            'entries/0GcLswTQ9oNGd3COkUfui5W0pBzlj7shL0HNTOQN.jpg',
        ];

        $image_width=['2','2','2','2','2','2','2'];

        $background_color_id=['8','8','8','8','8','8','8'];

        $button_link=
        [
           'google.com',
           'google.com',
           'google.com',
           'google.com',
           'google.com',
           'google.com',
           'google.com',
        ];

        $button_value=
        [
            'Learn More',
            'Read more',
            'Learn More',
            'Learn More',
            'Learn More',
            'Learn More',
            'Learn More',
        ];
        
        $event_category_id=['1','1','2','2','3','4','4'];


        $event_title=
        [
            'Celebration of Art',
            'War Never Ends',
            'One with Nature',
            'Sports for Health',
            'The Final Example', 
            'One More Example',
            'Nature is Therpay', 
        ];

        $event_text=
        [
            'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.', 
            
            'The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English.',

            'Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).',

            'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.',

            'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum',

            'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.',

            'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.'
        ];

        $event_date=
        [
            '11/3/2025',
            '11/4/2025',
            '12/2/2024',
            '11/7/2025',
            '11/10/2025',
            '11/10/2025',
            '11/11/2025',
        ];

        $event_start_time=
        [
            '13:30:00',
            '23:03:00',
            '2:30:00',
            '13:20:00',
            '20:30:00',
            '2:30:00',
            '16:00:00',
        ];

        $event_end_time=
        [
            '14:30:00',
            '14:30:00',
            '5:30:00',
            '15:30:00',
            '22:30:00',
            '4:30:00',
            '17:00:00',
        ];

        foreach($images as $key=>$image){
            $entry=new Entries();
            $entry->type_id='1';
            $entry->image=$image;
            $entry->image_featured=$image_featured[$key];
            $entry->image_width=$image_width[$key];
            $entry->background_color_id=$background_color_id[$key];
            $entry->button_link=$button_link[$key];
            $entry->button_value=$button_value[$key];
            $entry->event_category_id=$event_category_id[$key];
            $entry->event_title=$event_title[$key];
            $entry->event_text=$event_text[$key];
            $entry->event_date=date('y-m-d',strtotime($event_date[$key]));
            $entry->event_start_time=$event_start_time[$key];
            $entry->event_end_time=$event_end_time[$key];
            $entry->save();
        }*/


        Entries::insert(
            [
                [
                    "type_id" => 1,
                    "image" => "entries/qd6nO4xKbeIlQ3h4UEbZRRwF1B3ubjIALPvJIc4k.jpg",
                    "image_featured" => "entries/ZMNc58X6hdo11lWFCSgAPUoBPvveYxNOJ9liRNS6.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 1,
                    "event_title" => "Celebration of Art",
                    "event_title_arabic" => null,
                    "event_text" => "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-03",
                    "event_start_time" => "13:30:00",
                    "event_end_time" => "14:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/RqLxM6noQCBeUFQLQbq2oHFT5vs3qKQPpWHoW2rL.jpg",
                    "image_featured" => "entries/7c10thiwMvgmyzh7XGfmPYF7S8Z11sgHKhlk075P.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Read more",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 1,
                    "event_title" => "War Never Ends",
                    "event_title_arabic" => null,
                    "event_text" => "The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English.",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-04",
                    "event_start_time" => "23:03:00",
                    "event_end_time" => "14:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/OjCWB6nuBHGGVM4IgyC6TCBpdrlQ17I1S5Hx0SfC.jpg",
                    "image_featured" => "entries/CtHGHTQfRyHdka0esRnD0pdiIYjmlqI3IpuSE7ds.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 2,
                    "event_title" => "One with Nature",
                    "event_title_arabic" => null,
                    "event_text" => "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
                    "event_text_arabic" => null,
                    "event_date" => "2024-12-02",
                    "event_start_time" => "02:30:00",
                    "event_end_time" => "05:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/VRwhavcLy5uVmV0qAv7v4R6g8kd8uglWLegaV4Ut.jpg",
                    "image_featured" => "entries/b2dkCAtP6r44y5Qh8FH6Ht34ovPazMoI2Q6GU5n0.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 2,
                    "event_title" => "Sports for Health",
                    "event_title_arabic" => null,
                    "event_text" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words. The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \"de Finibus Bonorum et Malorum\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-07",
                    "event_start_time" => "13:20:00",
                    "event_end_time" => "15:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/9Fm9r5eNI9lKs8dhlyp9ce3nmJxwYm5WVs79jzxf.jpg",
                    "image_featured" => "entries/VeuBojTpKIwlCY5IuXiyXKVJw2QsW2DCtbNYWwAb.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 3,
                    "event_title" => "The Final Example",
                    "event_title_arabic" => null,
                    "event_text" => "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-10",
                    "event_start_time" => "20:30:00",
                    "event_end_time" => "22:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/LKJF31m7tJ2PFHOxDWO1JAhYdY2XfVIJIFD3ML3J.jpg",
                    "image_featured" => "entries/UrUR1Zozcej8zfs2bDfHsDTs3JU4iqfAqVfQVfj8.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 4,
                    "event_title" => "One More Example",
                    "event_title_arabic" => null,
                    "event_text" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-10",
                    "event_start_time" => "02:30:00",
                    "event_end_time" => "04:30:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 1,
                    "image" => "entries/6mFqY8D4DeZmny82KZwAfM2iX57SrMn9X3Wbmcwv.jpg",
                    "image_featured" => "entries/0GcLswTQ9oNGd3COkUfui5W0pBzlj7shL0HNTOQN.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 8,
                    "button_value" => "Learn More",
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => "google.com",
                    "event_category_id" => 4,
                    "event_title" => "Nature is Therpay",
                    "event_title_arabic" => null,
                    "event_text" => "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia.",
                    "event_text_arabic" => null,
                    "event_date" => "2025-11-11",
                    "event_start_time" => "16:00:00",
                    "event_end_time" => "17:00:00",
                    "event_calendar_view" => null,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-19 11:31:59",
                    "updated_at" => "2025-11-19 11:31:59",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 8,
                    "image" => "entries/m3gYEhuadnNzpz2NtSfgNNaEkQ8i1o0cTB6liH8K.png",
                    "image_featured" => "entries/YBlFX0ABtmlakmiXvTh53nq45wPz4qddKazQiXwv.png",
                    "image_full" => null,
                    "image_width" => null,
                    "background_color_id" => null,
                    "button_value" => null,
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => null,
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => "[]",
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => 4,
                    "external_title" => "Anti Harassment Policy",
                    "external_title_arabic" => "سياسة مناهضة التحرّش",
                    "external_link" => "https://www.arabculturefund.org/data/resources/151.pdf",
                    "created_at" => "2025-11-19 15:09:37",
                    "updated_at" => "2025-11-19 15:22:40",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 8,
                    "image" => "entries/QFxmBk0A4nXNhijAGCJQGLTDH74Qz2Pc5aQahzWo.png",
                    "image_featured" => "entries/V2JdK3ZXKa0VkygJgSlHHwpc7oJg1mF0xI0RCyDj.png",
                    "image_full" => null,
                    "image_width" => 3,
                    "background_color_id" => 5,
                    "button_value" => "more",
                    "button_value_arabic" => "المزيد",
                    "button_shape_id" => 1,
                    "button_hover_shape_id" => 3,
                    "button_link" => "https://www.flipsnack.com/arabculturefund/afac-annual-report-2024-arabic.html",
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => "[]",
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => 4,
                    "external_title" => "Annual Report 2020",
                    "external_title_arabic" => "التقرير السنوي 2020",
                    "external_link" => "https://www.flipsnack.com/arabculturefund/afac-annual-report-2024-arabic.html",
                    "created_at" => "2025-11-19 15:22:23",
                    "updated_at" => "2025-11-19 15:24:05",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 2,
                    "image" => "entries/1RCpDlrw4nNVZjsMwVh0QtHZm82yHcfbXGdS7y7W.jpg",
                    "image_featured" => "entries/CEg5QCkQNYxWEYm7l5tVY2E1pPaMriDAjDdHoyJL.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 7,
                    "button_value" => null,
                    "button_value_arabic" => null,
                    "button_shape_id" => 2,
                    "button_hover_shape_id" => 3,
                    "button_link" => null,
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => "Program Test",
                    "program_title_arabic" => "Program Test",
                    "program_text" => "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text</p>",
                    "program_text_arabic" => "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text</p>",
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-20 09:20:50",
                    "updated_at" => "2025-11-20 09:20:50",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 2,
                    "image" => "entries/8TUnCmMDo9ud0kOzfPRlColRXBGyF3A1cGyldIva.jpg",
                    "image_featured" => "entries/WiJKv0b3QxO984v6sI7FuZotiDpuCElgy2Wlcxtv.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 6,
                    "button_value" => null,
                    "button_value_arabic" => null,
                    "button_shape_id" => 2,
                    "button_hover_shape_id" => 2,
                    "button_link" => "google.com",
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => "Another Program ",
                    "program_title_arabic" => "Another Program ",
                    "program_text" => "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text</p>",
                    "program_text_arabic" => "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text</p>",
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-20 09:23:49",
                    "updated_at" => "2025-11-20 09:23:49",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 4,
                    "image" => "entries/oGsDTQo07KsbIMjHmJ2ANxPyHBIckClRVsvRDbEF.jpg",
                    "image_featured" => "entries/ELKbK6x1sl1YF6UTV3DWw5smu6MXdNmPREU0CNBp.jpg",
                    "image_full" => null,
                    "image_width" => 3,
                    "background_color_id" => 5,
                    "button_value" => null,
                    "button_value_arabic" => null,
                    "button_shape_id" => null,
                    "button_hover_shape_id" => null,
                    "button_link" => null,
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => "Noureddine Korek",
                    "grantee_name_arabic" => "Noureddine Korek",
                    "grantee_text" => "<p>Noureddine Korek</p>",
                    "grantee_text_arabic" => "<p>Noureddine Korek</p>",
                    "grantee_country_id" => 17,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-20 09:52:46",
                    "updated_at" => "2025-11-20 09:52:46",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 8,
                    "image" => "entries/TI19uSxzGjfh32ZoJ99UP37pqHUI0jwv5qNlhfIO.jpg",
                    "image_featured" => "entries/i9EOWsyFKMIbsFZ3pxq6UfZnwZUekpcsM8AHylaU.jpg",
                    "image_full" => null,
                    "image_width" => 2,
                    "background_color_id" => 5,
                    "button_value" => null,
                    "button_value_arabic" => null,
                    "button_shape_id" => 2,
                    "button_hover_shape_id" => 3,
                    "button_link" => null,
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => null,
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => null,
                    "resource_title_arabic" => null,
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => null,
                    "resource_tags" => null,
                    "resource_tags_arabic" => null,
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => 1,
                    "external_title" => "Nour sample",
                    "external_title_arabic" => "Nour sample",
                    "external_link" => "www.google.com",
                    "created_at" => "2025-11-20 10:03:48",
                    "updated_at" => "2025-11-20 10:03:48",
                    "deleted_at" => null
                ],
                [
                    "type_id" => 6,
                    "image" => "entries/n0S47Q6GD51QRVptmNh3MAnjQY4Kp7o8CV5fzQHD.png",
                    "image_featured" => "entries/IP7oOlomSe7Plqzv2tg2uOiEG7NxlQrglkB0oUYZ.gif",
                    "image_full" => "entries/GquHhGwqdmqJKvEKd7Beymkh0e7GkWx4OHc82pNk.png",
                    "image_width" => 3,
                    "background_color_id" => 8,
                    "button_value" => "Read the report",
                    "button_value_arabic" => "إقرأ التقرير",
                    "button_shape_id" => 2,
                    "button_hover_shape_id" => 3,
                    "button_link" => "https://www.flipsnack.com/arabculturefund/afac-annual-report-2024-arabic.html",
                    "event_category_id" => null,
                    "event_title" => null,
                    "event_title_arabic" => null,
                    "event_text" => null,
                    "event_text_arabic" => null,
                    "event_date" => null,
                    "event_start_time" => null,
                    "event_end_time" => null,
                    "event_calendar_view" => 0,
                    "program_title" => null,
                    "program_title_arabic" => null,
                    "program_text" => null,
                    "program_text_arabic" => null,
                    "program_status" => null,
                    "project_category_id" => null,
                    "project_title" => null,
                    "project_title_arabic" => null,
                    "project_text" => null,
                    "project_text_arabic" => null,
                    "project_countries_id" => "[]",
                    "project_program_year_id" => null,
                    "grantee_name" => null,
                    "grantee_name_arabic" => null,
                    "grantee_text" => null,
                    "grantee_text_arabic" => null,
                    "grantee_country_id" => null,
                    "jury_name" => null,
                    "jury_name_arabic" => null,
                    "jury_text" => null,
                    "jury_text_arabic" => null,
                    "jury_country_id" => null,
                    "resource_title" => "AFAC annual report 2024",
                    "resource_title_arabic" => "تقرير آفاق السنوي 2024",
                    "resource_text" => null,
                    "resource_text_arabic" => null,
                    "resource_date" => "2024-10-05",
                    "resource_tags" => "Report publication",
                    "resource_tags_arabic" => "تقرير منشور",
                    "news_title" => null,
                    "news_title_arabic" => null,
                    "news_text" => null,
                    "news_text_arabic" => null,
                    "news_date" => null,
                    "news_tags" => null,
                    "news_tags_arabic" => null,
                    "external_category_id" => null,
                    "external_title" => null,
                    "external_title_arabic" => null,
                    "external_link" => null,
                    "created_at" => "2025-11-20 13:12:57",
                    "updated_at" => "2025-11-20 13:17:45",
                    "deleted_at" => null
                ]
            ]
        );

    }
}
