<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Entries;

class JurorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $jurors = 
        [
            ['fullname_en' => 'Alya Sebti', 'fullname_ar' => 'علياء السبتي'],
            ['fullname_en' => 'Hoor Al Qasimi', 'fullname_ar' => 'حور القاسمي'],
            ['fullname_en' => 'Tarek Abou El Fetouh', 'fullname_ar' => 'طارق أبو الفتوح'],
            ['fullname_en' => 'Bashar Murkus', 'fullname_ar' => 'بشّار مرقص'],
            ['fullname_en' => 'Hala Omran', 'fullname_ar' => 'حلا عمران'],
            ['fullname_en' => 'Khalid Amine', 'fullname_ar' => 'خالد أمين'],
            ['fullname_en' => 'Carine Doumit', 'fullname_ar' => 'كارين ضومط'],
            ['fullname_en' => 'Diana El Jeiroudi', 'fullname_ar' => 'ديانا الجيرودي'],
            ['fullname_en' => 'Reda Benjelloun', 'fullname_ar' => 'رضا بن جلون'],
            ['fullname_en' => 'Ismail Nashef', 'fullname_ar' => 'اسماعيل ناشف'],
            ['fullname_en' => 'Maya Issam Kesrouany', 'fullname_ar' => 'مايا عصام كسرواني'],
            ['fullname_en' => 'Omar Fertat', 'fullname_ar' => 'عمر فرتات'],
            ['fullname_en' => 'Mohamed Somji', 'fullname_ar' => 'محمد سمجي'],
            ['fullname_en' => 'Rana ElNemr', 'fullname_ar' => 'رنا النمر'],
            ['fullname_en' => 'Adania Shibli', 'fullname_ar' => 'عدنيّة شبلي'],
            ['fullname_en' => 'Adnen Jdey', 'fullname_ar' => 'عدنان جدي'],
            ['fullname_en' => 'Najwa Ben Shatwan', 'fullname_ar' => 'نجوى بن شتوان'],
            ['fullname_en' => 'Zeina G. Halabi', 'fullname_ar' => 'زينة الحلبي'],
            ['fullname_en' => 'Hamdi Makhlouf', 'fullname_ar' => 'حمدي مخلوف'],
            ['fullname_en' => 'Maan Abu Taleb', 'fullname_ar' => 'معن أبو طالب'],
            ['fullname_en' => 'Rima Khcheich', 'fullname_ar' => 'ريما خشيش'],
            ['fullname_en' => 'Maria Daif', 'fullname_ar' => 'ماريا ضعيف'],
            ['fullname_en' => 'Rim Naguib', 'fullname_ar' => 'ريم نجيب'],
            ['fullname_en' => 'Rowaida Al Khulaidi', 'fullname_ar' => 'رويدة الخليدي'],
            ['fullname_en' => 'Raed Andoni', 'fullname_ar' => 'رائد أنضوني'],
            ['fullname_en' => 'Christoph Terhechte', 'fullname_ar' => 'كريستوف ترهيشتيه'],
            ['fullname_en' => 'Tala Hadid', 'fullname_ar' => 'تالا حديد'],
            ['fullname_en' => 'Fouad El Khoury', 'fullname_ar' => 'فؤاد الخوري'],
            ['fullname_en' => 'Susan Meiselas', 'fullname_ar' => 'سوزان مايسلاس'],
            ['fullname_en' => 'Wafaa Bilal', 'fullname_ar' => 'وفاء بلال'],
            ['fullname_en' => 'Ali El Adawi', 'fullname_ar' => 'علي العدوي'],
            ['fullname_en' => 'Hicham Lasri', 'fullname_ar' => 'هشام العسري'],
            ['fullname_en' => 'Kaouther Ben Hania', 'fullname_ar' => 'كوثر بن هنيّة'],
            ['fullname_en' => 'Ossama Mohammed', 'fullname_ar' => 'أسامة محمد'],
            ['fullname_en' => 'Sabine El Chamaa', 'fullname_ar' => 'سابين الشمعة'],
            ['fullname_en' => 'Yahya Abdallah', 'fullname_ar' => 'يحيى عبدلله'],
            ['fullname_en' => 'Ahmed Al-Khatib', 'fullname_ar' => 'أحمد الخطيب'],
            ['fullname_en' => 'Habib Dechraoui', 'fullname_ar' => 'حبيب دشراوي'],
            ['fullname_en' => 'Lama Hazboun', 'fullname_ar' => 'لمى حزبون'],
            ['fullname_en' => 'Driss Ksikes', 'fullname_ar' => 'إدريس كسيكس'],
            ['fullname_en' => 'Hanane Hajj Ali', 'fullname_ar' => 'حنان الحاج علي'],
            ['fullname_en' => 'Laila Soliman', 'fullname_ar' => 'ليلى سليمان'],
            ['fullname_en' => 'Aser El Saqqa', 'fullname_ar' => 'آسر السقّا'],
            ['fullname_en' => 'Maha El Nabawi', 'fullname_ar' => 'مهى النبوي'],
            ['fullname_en' => 'Omar Abi Azar', 'fullname_ar' => 'عمر أبي عازار'],
            ['fullname_en' => 'Khadija Hamdi Soussi', 'fullname_ar' => 'خديجة حمدي سوسي'],
            ['fullname_en' => 'Moataz Nasr', 'fullname_ar' => 'معتز نصر'],
            ['fullname_en' => 'Camille Laemle', 'fullname_ar' => 'كاميل لايمل'],
            ['fullname_en' => 'Jihan El-Tahri', 'fullname_ar' => 'جيهان الطاهري'],
            ['fullname_en' => 'Kamal Aljafari', 'fullname_ar' => 'كمال الجعفري'],
            ['fullname_en' => 'Tarek Al-Ghoussein', 'fullname_ar' => 'طارق الغصين'],
            ['fullname_en' => 'Michèle Tyan', 'fullname_ar' => 'ميشال تيان'],
            ['fullname_en' => 'Scandar Copti', 'fullname_ar' => 'اسكندر قبطي'],
            ['fullname_en' => 'Yassine Temlali', 'fullname_ar' => 'ياسين تملالي'],
            ['fullname_en' => 'Issa Boulos', 'fullname_ar' => 'عيسى بولس'],
            ['fullname_en' => 'Maryam Saleh', 'fullname_ar' => 'مريم صالح'],
            ['fullname_en' => 'Toufic Farroukh', 'fullname_ar' => 'توفيق فرّوخ'],
            ['fullname_en' => 'Carlos Chahine', 'fullname_ar' => 'كارلوس شاهين'],
            ['fullname_en' => 'Oussama Hallal', 'fullname_ar' => 'أسامة حلال'],
            ['fullname_en' => "Esra'a Al Shafei", 'fullname_ar' => 'اسراء الشافعي'],
            ['fullname_en' => 'Fadi Tofeili', 'fullname_ar' => 'فادي طفيلي'],
            ['fullname_en' => 'Salwa Mikdadi', 'fullname_ar' => 'سلوى مقدادي'],
            ['fullname_en' => 'Khalil Joreige', 'fullname_ar' => 'خليل جريج'],
            ['fullname_en' => 'Najlaa El Ageli', 'fullname_ar' => 'نجلا العاجلي'],
            ['fullname_en' => 'Shurooq Amin', 'fullname_ar' => 'شروق أمين'],
            ['fullname_en' => 'Ghalya Saadawi', 'fullname_ar' => 'غالية السعداوي'],
            ['fullname_en' => 'Hicham Falah', 'fullname_ar' => 'هشام فلاح'],
            ['fullname_en' => 'Jean-Pierre Rehm', 'fullname_ar' => 'جان-بيار رم'],
            ['fullname_en' => 'Laura Boushnak', 'fullname_ar' => 'لورا بوشناق'],
            ['fullname_en' => 'Danielle Arbid', 'fullname_ar' => 'دانيال عربيد'],
            ['fullname_en' => 'Ikbal Zalila', 'fullname_ar' => 'إقبال زليلة'],
            ['fullname_en' => 'Khalid Abdalla', 'fullname_ar' => 'خالد عبدالله'],
            ['fullname_en' => 'Ghalia Ben Ali', 'fullname_ar' => 'غالية بن علي'],
            ['fullname_en' => 'Lubnan Baalbaki', 'fullname_ar' => 'لبنان بعلبكي'],
            ['fullname_en' => 'Tamer Abu Ghazaleh', 'fullname_ar' => 'تامر أبو غزالة'],
            ['fullname_en' => 'Hussein Baydoun', 'fullname_ar' => 'حسين بيضون'],
            ['fullname_en' => 'Nedjma Hadj Benchelabi', 'fullname_ar' => 'نجمة حاج بن شلبي'],
            ['fullname_en' => 'Alma Salem', 'fullname_ar' => 'ألما سالم'],
            ['fullname_en' => 'Sandi Hilal', 'fullname_ar' => 'ساندي هلال'],
            ['fullname_en' => 'Kader Attia', 'fullname_ar' => 'قادر عطية'],
            ['fullname_en' => 'Marwan Rechmawi', 'fullname_ar' => 'مروان رشماوي'],
            ['fullname_en' => 'Reem Fadda', 'fullname_ar' => 'ريم فضّة'],
            ['fullname_en' => 'Hala Lotfy', 'fullname_ar' => 'هالة لطفي'],
            ['fullname_en' => 'Karim Traidia', 'fullname_ar' => 'كريم طريدية'],
            ['fullname_en' => 'Steven Markovitz', 'fullname_ar' => 'ستيفن ماركوفتز'],
            ['fullname_en' => 'Kaelen Wilson-Goldie', 'fullname_ar' => 'كايلن ويلسون-غولدي'],
            ['fullname_en' => 'Hania Mroué', 'fullname_ar' => 'هانيا مروه'],
            ['fullname_en' => 'Tahar Chikhaoui', 'fullname_ar' => 'الطاهر الشيخاوي'],
            ['fullname_en' => 'Charbel Rouhana', 'fullname_ar' => 'شربل روحانا'],
            ['fullname_en' => 'Fathi Salama', 'fullname_ar' => 'فتحي سلامة'],
            ['fullname_en' => 'Kamilya Jubran', 'fullname_ar' => 'كاميليا جبران'],
            ['fullname_en' => 'Haytham Abdula Razzak', 'fullname_ar' => 'هيثم عبد الله الرزاق'],
            ['fullname_en' => 'Najwa Kandakgi', 'fullname_ar' => 'نجوى قندقجي'],
            ['fullname_en' => 'Randa Asmar', 'fullname_ar' => 'رنده أسمر'],
            ['fullname_en' => 'Anas (Anders) Hastrup', 'fullname_ar' => 'أنس هاستروب'],
            ['fullname_en' => 'Reem Khattab', 'fullname_ar' => 'ريم خطاب'],
            ['fullname_en' => 'Sultan Al-Bazie', 'fullname_ar' => 'سلطان بن عبدالرحمن البازعي'],
            ['fullname_en' => 'Abdelkader Damani', 'fullname_ar' => 'عبد القادر دماني'],
            ['fullname_en' => 'Farid Al-Zahi', 'fullname_ar' => 'فريد الزاهي'],
            ['fullname_en' => 'Saleh Barakat', 'fullname_ar' => 'صالح بركات'],
            ['fullname_en' => 'Ahmed El Attar', 'fullname_ar' => 'أحمد العطار'],
            ['fullname_en' => 'Moukhtar Kocache', 'fullname_ar' => 'مختار كوكش'],
            ['fullname_en' => 'Chokri Al Mabkhout', 'fullname_ar' => 'شكري المبخوت'],
            ['fullname_en' => 'Ammar Dajani', 'fullname_ar' => 'عمار دجاني'],
            ['fullname_en' => 'Brahim El Mazned', 'fullname_ar' => 'براهيم المزند'],
            ['fullname_en' => 'Tarek Yamani', 'fullname_ar' => 'طارق يمني'],
            ['fullname_en' => 'Fadi Abi Samra', 'fullname_ar' => 'فادي أبي سمرا'],
            ['fullname_en' => 'Mahmoud El Lozy', 'fullname_ar' => 'محمود اللوزي'],
            ['fullname_en' => 'Sawsan Darwaza', 'fullname_ar' => 'سوسن دروزة'],
            ['fullname_en' => 'Ali Shaath', 'fullname_ar' => 'علي شعث'],
            ['fullname_en' => 'Joumana Al Jabri', 'fullname_ar' => 'جمانة الجابري'],
            ['fullname_en' => 'Nadine Touma', 'fullname_ar' => 'نادين توما'],
            ['fullname_en' => 'Mohammed Djehiche', 'fullname_ar' => 'محمد جحيش'],
            ['fullname_en' => 'Rachida Triki', 'fullname_ar' => 'رشيدة تريكي'],
            ['fullname_en' => 'Samar Martha', 'fullname_ar' => 'سمر مارتا'],
            ['fullname_en' => 'Abdulkhaleq Abdulla', 'fullname_ar' => 'عبدالخالق عبدالله'],
            ['fullname_en' => 'Khalil Sweileh', 'fullname_ar' => 'خليل صويلح'],
            ['fullname_en' => 'Rasha El Ameer', 'fullname_ar' => 'رشا الأمير'],
            ['fullname_en' => 'Nejib Belkadhi', 'fullname_ar' => 'نجيب بالقاضي'],
            ['fullname_en' => 'Rasha Salti', 'fullname_ar' => 'رشا سلطي'],
            ['fullname_en' => 'Ziad Khatlan', 'fullname_ar' => 'زياد خطلان'],
            ['fullname_en' => 'Isabel Arrate Fernandez', 'fullname_ar' => 'إزابيل أرراتي فرناندز'],
            ['fullname_en' => 'Mikael Opstrup', 'fullname_ar' => 'مخايل أبستروب'],
            ['fullname_en' => 'Bruni Burres', 'fullname_ar' => 'بروني بورس'],
            ['fullname_en' => 'Joanna Hadjithomas', 'fullname_ar' => 'جوانا حاجي توما'],
            ['fullname_en' => 'Kirsten Johnson', 'fullname_ar' => 'كيرستن جونسون'],
            ['fullname_en' => 'Masoud Amrallah Al-Ali', 'fullname_ar' => 'مسعود أمرالله العلي'],
            ['fullname_en' => 'Rajaa Ammari', 'fullname_ar' => 'رجاء عمّاري'],
            ['fullname_en' => 'Wael Abd Al-Fattah', 'fullname_ar' => 'وائل عبدالفتّاح'],
            ['fullname_en' => 'Ziad Doueiri', 'fullname_ar' => 'زياد دويري'],
            ['fullname_en' => 'Ibrahim Nasrallah', 'fullname_ar' => 'إبراهيم نصرالله'],
            ['fullname_en' => "Mo'jab Al-Zahrani", 'fullname_ar' => 'معجب الزهراني'],
            ['fullname_en' => 'Ali Osman', 'fullname_ar' => 'علي عثمان'],
            ['fullname_en' => 'Zaid Jabri', 'fullname_ar' => 'زيد جبري'],
            ['fullname_en' => 'Zeid Hamdan', 'fullname_ar' => 'زيد حمدان'],
            ['fullname_en' => 'Issam Bou Khaled', 'fullname_ar' => 'عصام بوخالد'],
            ['fullname_en' => 'Raed Asfour', 'fullname_ar' => 'رائد عصفور'],
            ['fullname_en' => 'Bayan Kanoo', 'fullname_ar' => 'بيان كانو'],
            ['fullname_en' => 'Ferial Ghazoul', 'fullname_ar' => 'فريال غزول'],
            ['fullname_en' => 'Ranwa Yehya', 'fullname_ar' => 'رنوة يحيى'],
            ['fullname_en' => 'Gilbert Hage', 'fullname_ar' => 'جيلبير الحاج'],
            ['fullname_en' => 'Cara Mertes', 'fullname_ar' => 'كارا مرتز'],
            ['fullname_en' => 'Joslyn Barnes', 'fullname_ar' => 'جوسلين بارنز'],
            ['fullname_en' => 'Khalil Benkirane', 'fullname_ar' => 'خليل بن كيران'],
            ['fullname_en' => 'Elia Suleiman', 'fullname_ar' => 'إليا سليمان'],
            ['fullname_en' => 'Faouzi Bensaidi', 'fullname_ar' => 'فوزي بن السعيدي'],
            ['fullname_en' => 'Farida Benlyazid', 'fullname_ar' => 'فريدة بن اليزيد'],
            ['fullname_en' => 'Rania Stephan', 'fullname_ar' => 'رانيا اسطفان'],
            ['fullname_en' => 'Marwan Abado', 'fullname_ar' => 'مروان عبادو'],
            ['fullname_en' => 'Sami Ben Said', 'fullname_ar' => 'سامي بن سعيد'],
            ['fullname_en' => 'Latifa Lahrarre', 'fullname_ar' => 'لطيفة الأحرار'],
            ['fullname_en' => 'Lina Abyad', 'fullname_ar' => 'لينا أبيض'],
            ['fullname_en' => 'Fadil Khalel', 'fullname_ar' => 'فاضل خليل'],
            ['fullname_en' => 'Ayman Bardawil', 'fullname_ar' => 'أيمن بردويل'],
            ['fullname_en' => 'Manal Abaza', 'fullname_ar' => 'منال أباظة'],
            ['fullname_en' => 'Nizar Rammal', 'fullname_ar' => 'نزار رمّال'],
            ['fullname_en' => 'Asem Al Bacha', 'fullname_ar' => 'عاصم الباشا'],
            ['fullname_en' => 'Kamal Boullata', 'fullname_ar' => 'كمال بلّاطة'],
            ['fullname_en' => 'Bruno Boudjelal', 'fullname_ar' => 'برونو بو جلال'],
            ['fullname_en' => 'Gregory Buchakjian', 'fullname_ar' => 'جريجوري بوشاكجيان'],
            ['fullname_en' => 'Fatma Kilani', 'fullname_ar' => 'فاطمة كيلاني'],
            ['fullname_en' => 'Manal AlDowayan', 'fullname_ar' => 'منال الضويان'],
            ['fullname_en' => 'Hassan Khan', 'fullname_ar' => 'حسن خان'],
            ['fullname_en' => 'Amer Shomali', 'fullname_ar' => 'عامر شوملي'],
            ['fullname_en' => 'Hala Galal', 'fullname_ar' => 'هالة جلال'],
            ['fullname_en' => 'Ayman A. El-Desouky', 'fullname_ar' => 'أيمن أ. الدسوقي'],
            ['fullname_en' => 'Rana Issa', 'fullname_ar' => 'رنا عيسى'],
            ['fullname_en' => 'Sinan Antoon', 'fullname_ar' => 'سنان أنطون'],
            ['fullname_en' => 'Rasha Salah', 'fullname_ar' => 'رشا صلاح'],
            ['fullname_en' => 'Mona Younis', 'fullname_ar' => 'منى يونس'],
            ['fullname_en' => 'Sana Ouchtati', 'fullname_ar' => 'سناء أشتاتي'],
            ['fullname_en' => 'Ala Hleihel', 'fullname_ar' => 'علاء حليحل'],
            ['fullname_en' => 'Youssef Rakha', 'fullname_ar' => 'يوسف رخا'],
            ['fullname_en' => 'Zied Zouari', 'fullname_ar' => 'زياد زواري'],
            ['fullname_en' => 'Rami Abadir', 'fullname_ar' => 'رامي ابادير'],
            ['fullname_en' => 'Hanane Kassab', 'fullname_ar' => 'حنان قصاب'],
            ['fullname_en' => 'Sarah Rifky', 'fullname_ar' => 'سارة رفقي'],
            ['fullname_en' => 'Moez Mrabet', 'fullname_ar' => 'معز مرابط'],
            ['fullname_en' => 'Maha Maamoun', 'fullname_ar' => 'مها مأمون'],
            ['fullname_en' => 'Khadija El Bannaoui', 'fullname_ar' => 'خديجة البنّاوي'],
            ['fullname_en' => 'Zeina Arida', 'fullname_ar' => 'زينة عريضة'],
            ['fullname_en' => 'Ahmed El Maanouni', 'fullname_ar' => 'أحمد المعنوني'],
            ['fullname_en' => 'Habiba Djahnine', 'fullname_ar' => 'حبيبة جهنين'],
            ['fullname_en' => 'Faouzia Sahly', 'fullname_ar' => 'فوزية الساحلي'],
            ['fullname_en' => 'Nidhal Guiga', 'fullname_ar' => 'نضال قيقة'],
            ['fullname_en' => 'Rola Kobeissi', 'fullname_ar' => 'رلى القبيسي'],
            ['fullname_en' => 'Zeina Maasri', 'fullname_ar' => 'زينة معاصري'],
            ['fullname_en' => 'Ali Essafi', 'fullname_ar' => 'علي الصافي'],
            ['fullname_en' => 'Dora Bouchoucha', 'fullname_ar' => 'درّة بوشوشة'],
            ['fullname_en' => 'Marwa Seoudi', 'fullname_ar' => 'مروة السعودي'],
            ['fullname_en' => 'Irit Neidhart', 'fullname_ar' => 'إريت نايدهارت'],
            ['fullname_en' => 'Mohammed Soueid', 'fullname_ar' => 'محمد سويد'],
            ['fullname_en' => 'Alawiya Sobh', 'fullname_ar' => 'علوية صبح'],
            ['fullname_en' => 'Najwan Darwish', 'fullname_ar' => 'نجوان درويش'],
            ['fullname_en' => 'Nouri Al-Jarrah', 'fullname_ar' => 'نوري الجراح'],
            ['fullname_en' => 'Jack Persekian', 'fullname_ar' => 'جاك برسكيان'],
            ['fullname_en' => 'Walid Sadek', 'fullname_ar' => 'وليد صادق'],
            ['fullname_en' => 'Abdellah Karroum', 'fullname_ar' => 'عبدالله كرّوم'],
            ['fullname_en' => 'Ahmad Baydoun', 'fullname_ar' => 'أحمد بيضون'],
            ['fullname_en' => 'Amine Al Zaoui', 'fullname_ar' => 'أمين الزاوي'],
            ['fullname_en' => 'Ezzat Al Kamhawi', 'fullname_ar' => 'عزت قمحاوي'],
            ['fullname_en' => 'Fadhil Al Azzawi', 'fullname_ar' => 'فاضل العزّاوي'],
            ['fullname_en' => 'Khaled Jubran', 'fullname_ar' => 'خالد جبران'],
            ['fullname_en' => 'Marie-Therese Abdel Messih', 'fullname_ar' => 'ماري تيريز عبدالمسيح'],
            ['fullname_en' => 'Michel Khleifi', 'fullname_ar' => 'ميشيل خليفي'],
            ['fullname_en' => 'Nadia Kamel', 'fullname_ar' => 'ناديا كامل'],
            ['fullname_en' => 'Said Murad', 'fullname_ar' => 'سعيد مراد'],
            ['fullname_en' => 'Vera Tamari', 'fullname_ar' => 'فيرا تماري'],
            ['fullname_en' => 'Sawsan Jafar', 'fullname_ar' => 'سوسن جعفر'],
            ['fullname_en' => 'Elias Farkouh', 'fullname_ar' => 'إلياس فركوح'],
            ['fullname_en' => 'Faouzi Skali', 'fullname_ar' => 'فوزي الصقلي'],
            ['fullname_en' => 'Hani Kalouti', 'fullname_ar' => 'هاني كالوتي'],
            ['fullname_en' => 'Jamal Al Ghitany', 'fullname_ar' => 'جمال الغيطاني'],
            ['fullname_en' => 'Jeryes Samawi', 'fullname_ar' => 'جريس سماوي'],
            ['fullname_en' => 'Khaled Mattawa', 'fullname_ar' => 'خالد المطاوع'],
            ['fullname_en' => 'Khaled Mohammed Ali', 'fullname_ar' => 'خالد محمد علي'],
            ['fullname_en' => 'Marie Elias', 'fullname_ar' => 'ماري إلياس'],
            ['fullname_en' => 'Mohammed Al Rashdi', 'fullname_ar' => 'محمد الراشدي'],
            ['fullname_en' => 'Nadira Laggoune', 'fullname_ar' => 'نظيرة العقون'],
            ['fullname_en' => 'Qassem Haddad', 'fullname_ar' => 'قاسم حداد'],
            ['fullname_en' => 'Samia Mehrez', 'fullname_ar' => 'سامية محرز'],
            ['fullname_en' => 'Talal Mualla', 'fullname_ar' => 'طلال معلا'],
            ['fullname_en' => 'Ahmad Mualla', 'fullname_ar' => 'أحمد معلا'],
            ['fullname_en' => 'Ali Abou Shadi', 'fullname_ar' => 'علي أبو شادي'],
            ['fullname_en' => 'Amjad Nasser', 'fullname_ar' => 'أمجد ناصر'],
            ['fullname_en' => 'Andre Al Haje', 'fullname_ar' => 'أندريه الحاج'],
            ['fullname_en' => 'Azza Madian', 'fullname_ar' => 'عزة مدين'],
            ['fullname_en' => 'Basma El Husseiny', 'fullname_ar' => 'بسمة الحسيني'],
            ['fullname_en' => 'Christine Tohme', 'fullname_ar' => 'كريستين طعمة'],
            ['fullname_en' => 'Ibrahim Al Ariss', 'fullname_ar' => 'إبراهيم العريس'],
            ['fullname_en' => 'Jalila Baccar', 'fullname_ar' => 'جليلة بكّار'],
            ['fullname_en' => 'Laila Hourani', 'fullname_ar' => 'ليلى حوراني'],
            ['fullname_en' => 'Marianne Khoury', 'fullname_ar' => 'ماريان خوري'],
            ['fullname_en' => 'Menha Batraoui', 'fullname_ar' => 'منحة البطراوي'],
            ['fullname_en' => 'Mohammed Makhlouf', 'fullname_ar' => 'محمد مخلوف'],
            ['fullname_en' => 'Peirre Abi Saab', 'fullname_ar' => 'بيار أبي صعب'],
            ['fullname_en' => 'Taleb Al Refaie', 'fullname_ar' => 'طالب الرفاعي'],
            ['fullname_en' => 'Taoufik Jebali', 'fullname_ar' => 'توفيق جبالي'],
            ['fullname_en' => 'Abbas Beydoun', 'fullname_ar' => 'عباس بيضون'],
            ['fullname_en' => 'Abdo Wazen', 'fullname_ar' => 'عبده وازن'],
            ['fullname_en' => 'Alia Arasoughly', 'fullname_ar' => 'علياء ارصغلي'],
            ['fullname_en' => 'Elias Khoury', 'fullname_ar' => 'إلياس خوري'],
            ['fullname_en' => 'Ibrahim Jaber Ibrahim', 'fullname_ar' => 'إبراهيم جابر إبراهيم'],
            ['fullname_en' => 'Jaber Asfour', 'fullname_ar' => 'جابر عصفور'],
            ['fullname_en' => 'Marcel Khalife', 'fullname_ar' => 'مارسل خليفة'],
            ['fullname_en' => 'Oussama Ghanam', 'fullname_ar' => 'أسامة غنم'],
            ['fullname_en' => 'Rana Sadik', 'fullname_ar' => 'رنا صادق'],
            ['fullname_en' => 'Salma Feriani', 'fullname_ar' => 'سلمى فرياني'],
            ['fullname_en' => 'Sulayman Al Bassam', 'fullname_ar' => 'سليمان البسام'],
            ['fullname_en' => 'Kristen Lubben', 'fullname_ar' => 'كريستين لوبن'],
            ['fullname_en' => 'Yasmine Eid-Sabbagh', 'fullname_ar' => 'ياسمين عيد صبّاغ'],
            ['fullname_en' => 'Zied Ben Romdhane', 'fullname_ar' => 'زياد بن رمضان'],
            ['fullname_en' => 'Arafat Sadallah', 'fullname_ar' => 'عرفات سعد الله'],
            ['fullname_en' => 'Lara Khaldi', 'fullname_ar' => 'لارا خالدي'],
            ['fullname_en' => 'Salah Hassan', 'fullname_ar' => 'صلاح حسن'],
            ['fullname_en' => 'Carole Abboud', 'fullname_ar' => 'كارول عبود'],
            ['fullname_en' => 'Karima Mansour', 'fullname_ar' => 'كريمة منصور'],
            ['fullname_en' => 'Mustapha Benfodil', 'fullname_ar' => 'مصطفى بن فوضيل'],
            ['fullname_en' => 'Vartan Avakian', 'fullname_ar' => 'فارتان أفاكيان'],
            ['fullname_en' => 'Djamel Kerkar', 'fullname_ar' => 'جمال كركار'],
            ['fullname_en' => 'Saima Samoud', 'fullname_ar' => 'سيما صمود'],
            ['fullname_en' => 'Basel Rajoub', 'fullname_ar' => 'باسل رجوب'],
            ['fullname_en' => 'Mazen El-Sayed', 'fullname_ar' => 'مازن السيد'],
            ['fullname_en' => 'Aseel Sawalha', 'fullname_ar' => 'أسيل صوالحة'],
            ['fullname_en' => 'Omar Berrada', 'fullname_ar' => 'عمر برادة'],
            ['fullname_en' => 'Kirsten Scheid', 'fullname_ar' => 'كيرستن شيد'],
            ['fullname_en' => 'Tarek El-Ariss', 'fullname_ar' => 'طارق العريس'],
            ['fullname_en' => 'Alia Moussallam', 'fullname_ar' => 'عليا مسلّم'],
            ['fullname_en' => 'Ghassan Salhab', 'fullname_ar' => 'غسان سلهب'],
            ['fullname_en' => 'Fatema Loukili', 'fullname_ar' => 'فاطمة الوكيلي'],
            ['fullname_en' => 'Hajooj Kuka', 'fullname_ar' => 'حجوج كوكا'],
            ['fullname_en' => 'Dalia Khamissy', 'fullname_ar' => 'داليا الخميسي'],
            ['fullname_en' => 'Ghaith Abdul-Ahad', 'fullname_ar' => 'غيث عبد الأحد'],
            ['fullname_en' => 'Bouchra Khalili', 'fullname_ar' => 'بشرى خليلي'],
            ['fullname_en' => 'Bassam El Baroni', 'fullname_ar' => 'بسام الباروني'],
            ['fullname_en' => 'Rayyane Tabet', 'fullname_ar' => 'ريان تابت'],
            ['fullname_en' => 'Jinane Dagher', 'fullname_ar' => 'جنان داغر'],
            ['fullname_en' => 'Qutaiba Barhamji', 'fullname_ar' => 'قتيبة بهرمجي'],
            ['fullname_en' => 'Nadir Bouhmouch', 'fullname_ar' => 'نادر بوحموش'],
            ['fullname_en' => 'Lobna Mlika', 'fullname_ar' => 'لبنا مليكا'],
            ['fullname_en' => 'Krystel Khoury', 'fullname_ar' => 'كريستل خوري'],
            ['fullname_en' => 'Mohammad Al Attar', 'fullname_ar' => 'محمد العطار'],
            ['fullname_en' => 'Iman Mersal', 'fullname_ar' => 'إيمان مرسال'],
            ['fullname_en' => 'Hilal Chouman', 'fullname_ar' => 'هلال شومان'],
            ['fullname_en' => 'Amira Ghenim', 'fullname_ar' => 'أميرة غنيم'],
            ['fullname_en' => 'Mohammed Abdallah', 'fullname_ar' => 'محمد عبد الله'],
            ['fullname_en' => 'Neila Tazi', 'fullname_ar' => 'نائلة التازي'],
            ['fullname_en' => 'Fatin Farhat', 'fullname_ar' => 'فاتن فرحات'],
            ['fullname_en' => 'Dalia Daoud', 'fullname_ar' => 'داليا داود'],
            ['fullname_en' => 'Hicham Bouzid', 'fullname_ar' => 'هشام بوزيد'],
            ['fullname_en' => 'Joelle Khoury', 'fullname_ar' => 'جويل خوري'],
            ['fullname_en' => 'Zainab Guedira', 'fullname_ar' => 'زينب قديرة'],
            ['fullname_en' => 'Muqata\'a', 'fullname_ar' => 'مقاطعة'],
            ['fullname_en' => 'Ala Younis', 'fullname_ar' => 'آلاء يونس'],
            ['fullname_en' => 'Faten I. Morsy', 'fullname_ar' => 'فاتن إسماعيل مرسي'],
            ['fullname_en' => 'Yazid Anani', 'fullname_ar' => 'يزيد عناني'],
            ['fullname_en' => 'Yasmina Naji', 'fullname_ar' => 'ياسمينة ناجي'],
            ['fullname_en' => 'Nisreen Naffa', 'fullname_ar' => 'نسرين نفّاع'],
            ['fullname_en' => 'Mohamed Allam', 'fullname_ar' => 'محمد علّام'],
            ['fullname_en' => 'Deena Abdelwahed', 'fullname_ar' => 'دينا عبد الواحد'],
            ['fullname_en' => 'Othman Nejmeddine', 'fullname_ar' => 'عثمان نجم الدين'],
            ['fullname_en' => 'Johnny Farraj', 'fullname_ar' => 'جوني فرّاج'],
            ['fullname_en' => 'Khaled Malas', 'fullname_ar' => 'خالد ملص'],
            ['fullname_en' => 'Malek Gnaoui', 'fullname_ar' => 'مالك قناوي'],
            ['fullname_en' => 'Toleen Touq', 'fullname_ar' => 'تولين طوق'],
            ['fullname_en' => 'Nora Amin', 'fullname_ar' => 'نورا أمين'],
            ['fullname_en' => 'Mounzer Baalbaki', 'fullname_ar' => 'مُنذر بعلبكي'],
            ['fullname_en' => 'Kamal Khalladi', 'fullname_ar' => 'كمال خلادي'],
            ['fullname_en' => 'Ghada Sayegh', 'fullname_ar' => 'غادة الصايغ'],
            ['fullname_en' => 'Nadine Khan', 'fullname_ar' => 'نادين خان'],
            ['fullname_en' => 'Ely Dagher', 'fullname_ar' => 'إيلي داغر'],
            ['fullname_en' => 'Leila Arman', 'fullname_ar' => 'ليلى أرمن'],
            ['fullname_en' => 'Youssef Chebbi', 'fullname_ar' => 'يوسف الشابي'],
            ['fullname_en' => 'Heba elCheikh', 'fullname_ar' => 'هبة الشيخ'],
            ['fullname_en' => 'Dr. Khaldun Bshara', 'fullname_ar' => 'د. خلدون بشارة'],
            ['fullname_en' => 'Ahmed Amine Azouzi', 'fullname_ar' => 'أحمد أمين عزوزي'],
            ['fullname_en' => 'Eliane Raheb', 'fullname_ar' => 'إليان الراهب'],
            ['fullname_en' => 'Mohanad Yaqubi', 'fullname_ar' => 'مهند يعقوبي'],
            ['fullname_en' => 'Sara Ishaq', 'fullname_ar' => 'سارة إسحاق'],
            ['fullname_en' => 'Nidhal Chamekh', 'fullname_ar' => 'نضال الشامخ'],
            ['fullname_en' => 'Reem Shadid', 'fullname_ar' => 'ريم شديد'],
            ['fullname_en' => 'Doa Aly', 'fullname_ar' => 'دعاء علي'],
            ['fullname_en' => 'Maya Abu al-Hayat', 'fullname_ar' => 'مايا أبو الحيات'],
            ['fullname_en' => 'Ahmed Nagy', 'fullname_ar' => 'أحمد ناجى'],
            ['fullname_en' => 'Soukaina Habiballah', 'fullname_ar' => 'سكينة حبيب الله'],
            ['fullname_en' => 'George Bajalia', 'fullname_ar' => 'جورج باجالية'],
            ['fullname_en' => 'Marianne Noujaim', 'fullname_ar' => 'ماريان نجيم'],
            ['fullname_en' => 'Youness Atbane', 'fullname_ar' => 'يونس عتبان'],
            ['fullname_en' => 'Hasan Hujairi', 'fullname_ar' => 'حسن الحجيري'],
            ['fullname_en' => 'Widad Mjama', 'fullname_ar' => 'وداد مجمع'],
            ['fullname_en' => 'Fadi El Abdallah', 'fullname_ar' => 'فادي العبد الله'],
            ['fullname_en' => 'Omayma Abdelshafy', 'fullname_ar' => 'أُميمة عبد الشافي'],
            ['fullname_en' => 'Yazan Khalili', 'fullname_ar' => 'يزن خليلي'],
            ['fullname_en' => 'Samia Labidi', 'fullname_ar' => 'سامية العبيدي'],
            ['fullname_en' => 'Nadine Salib', 'fullname_ar' => 'نادين صليب'],
            ['fullname_en' => 'Kais Zaied', 'fullname_ar' => 'قيس زايد'],
            ['fullname_en' => 'Tania El Khoury', 'fullname_ar' => 'تانيا الخوري'],
            ['fullname_en' => 'Sabine Sidawi', 'fullname_ar' => 'سابين صيداوي'],
            ['fullname_en' => 'Ayten Amin', 'fullname_ar' => 'أيتن أمين'],
            ['fullname_en' => 'Ala Eddine Slim', 'fullname_ar' => 'علاء الدين سليم'],
            ['fullname_en' => 'Heba Hage Felder', 'fullname_ar' => 'هبة الحاج فيلدر'],
            ['fullname_en' => 'Nariman El-Mofty', 'fullname_ar' => 'ناريمان المفتي'],
            ['fullname_en' => 'Jessica Murray', 'fullname_ar' => 'جيسيكا موراي'],
            ['fullname_en' => 'Hrair Sarkissian', 'fullname_ar' => 'هراير سركيسيان'],
            ['fullname_en' => 'Nadia Bseiso', 'fullname_ar' => 'نادية بسيسو'],
            ['fullname_en' => 'Lydia Haddag', 'fullname_ar' => 'ليديا حدّاق'],
            ['fullname_en' => 'Rachid Briki', 'fullname_ar' => 'رشيد بريكي'],
            ['fullname_en' => 'Salah Badis', 'fullname_ar' => 'صلاح باديس'],
            ['fullname_en' => 'Fatma Ghandour', 'fullname_ar' => 'فاطمة غندور'],
            ['fullname_en' => 'Hadia Gana', 'fullname_ar' => 'هادية قانة'],
            ['fullname_en' => 'Leila Tayeb', 'fullname_ar' => 'ليلى طيب'],
            ['fullname_en' => 'Bassem Yousri', 'fullname_ar' => 'باسم يسري'],
            ['fullname_en' => 'Therese Ghobriel', 'fullname_ar' => 'تريز غبريال'],
            ['fullname_en' => 'Rajae Slimani', 'fullname_ar' => 'رجاء السليماني'],
            ['fullname_en' => 'Cyrine Gannoun', 'fullname_ar' => 'سيرين قنون'],
            ['fullname_en' => 'Nanda Mohammad', 'fullname_ar' => 'ناندا محمد'],
            ['fullname_en' => 'Taoufiq Izeddiou', 'fullname_ar' => 'توفيق إزيديو'],
            ['fullname_en' => 'Beya Othmani', 'fullname_ar' => 'بية عثماني'],
            ['fullname_en' => 'Bochra Triki', 'fullname_ar' => 'بشرى التريكي'],
            ['fullname_en' => 'Soumaya Gharsallah', 'fullname_ar' => 'سُميّة غرس الله'],
            ['fullname_en' => 'Farouk Mardam-Bey', 'fullname_ar' => 'فاروق مردم بك'],
            ['fullname_en' => 'Ghazi Gheblawi', 'fullname_ar' => 'غازي القبلاوي'],
            ['fullname_en' => 'Mansoura Ez-Eldin', 'fullname_ar' => 'منصورة عز الدين'],
            ['fullname_en' => 'Nadia Kaabi-Linke', 'fullname_ar' => 'نادية الكعبي-لينكه'],
            ['fullname_en' => 'Khaled Bouzidi', 'fullname_ar' => 'خالد بوزيدي'],
            ['fullname_en' => 'Azza Chaabouni', 'fullname_ar' => 'عزة شعبوني'],
            ['fullname_en' => 'Karim Aitouna', 'fullname_ar' => 'كريم أيتونا'],
            ['fullname_en' => 'Mohammad Shawky Hassan', 'fullname_ar' => 'محمد شوقي حسن'],
            ['fullname_en' => 'Sarah El Miniawy', 'fullname_ar' => 'سارة المنياوي'],
            ['fullname_en' => 'Imed Alibi', 'fullname_ar' => 'عماد عليبي'],
            ['fullname_en' => 'Tareq Rantisi', 'fullname_ar' => 'طارق رنتيسي'],
            ['fullname_en' => 'Belhassen Handous', 'fullname_ar' => 'بلحسن حندوس'],
            ['fullname_en' => 'Layal Ftouni', 'fullname_ar' => 'ليال فتوني'],
            ['fullname_en' => 'Nour El Safoury', 'fullname_ar' => 'نور الصافوري'],
            ['fullname_en' => 'Youssef Shazli', 'fullname_ar' => 'يوسف شاذلي'],
            ['fullname_en' => 'Rania Rafei', 'fullname_ar' => 'رانيا رافعي'],
            ['fullname_en' => 'Amr Gamal', 'fullname_ar' => 'عمرو جمال'],
            ['fullname_en' => 'Georges Hachem', 'fullname_ar' => 'جورج الهاشم'],
            ['fullname_en' => 'Yasmine Zohdi', 'fullname_ar' => 'ياسمين زهدي'],
            ['fullname_en' => 'Nadim Cheikhrouha', 'fullname_ar' => 'نديم شيخ روحه'],
            ['fullname_en' => 'Nadia Eliewat', 'fullname_ar' => 'نادية عليوات'],
            ['fullname_en' => 'Pamela Ghanime', 'fullname_ar' => 'باميلا غنيمة'],
            ['fullname_en' => 'Nada Riyadh', 'fullname_ar' => 'ندى رياض'],
            ['fullname_en' => 'Heba Farid', 'fullname_ar' => 'هبة فريد'],
            ['fullname_en' => 'Rula Halawani', 'fullname_ar' => 'رلى حلواني'],
            ['fullname_en' => 'Sabiha Çimen', 'fullname_ar' => 'صبيحة سيمين'],
            ['fullname_en' => 'Ismail Ghazali', 'fullname_ar' => 'إسماعيل غزالي'],
            ['fullname_en' => 'Mohamed Shoair', 'fullname_ar' => 'محمد شعير'],
            ['fullname_en' => 'Nisrine Al Zahre', 'fullname_ar' => 'نسرين الزهر'],
            ['fullname_en' => 'Gladys Joujou', 'fullname_ar' => 'غلاديس جوجو'],
            ['fullname_en' => 'Laila Aoudj', 'fullname_ar' => 'ليلى أعوج'],
            ['fullname_en' => 'Marouan Omara', 'fullname_ar' => 'مروان عمارة'],
            ['fullname_en' => 'Mohamad Al Rashi', 'fullname_ar' => 'محمد آل راشي'],
            ['fullname_en' => 'Amina Menia', 'fullname_ar' => 'أمينة منيا'],
            ['fullname_en' => 'Yasmine Nachabe Taan', 'fullname_ar' => 'ياسمين نشابة طعان'],
            ['fullname_en' => 'Noma Omran', 'fullname_ar' => 'نعمى عمران'],
            ['fullname_en' => 'Raed Yassin', 'fullname_ar' => 'رائد ياسين'],
            ['fullname_en' => 'El Mehdi Nassouli', 'fullname_ar' => 'لمهدي الناسولي'],
            ['fullname_en' => 'Samar Dudin', 'fullname_ar' => 'سمر دودين'],
            ['fullname_en' => 'Fatma Cherif', 'fullname_ar' => 'فاطمة شريف'],
            ['fullname_en' => 'Chaymaa Ramzi', 'fullname_ar' => 'شيماء رمزي'],
            ['fullname_en' => 'Nour Ouayda', 'fullname_ar' => 'نور عويضة'],
            ['fullname_en' => 'Ahmad Al-Ayyad', 'fullname_ar' => 'أحمد العياد'],
            ['fullname_en' => 'Muhammad Taymour', 'fullname_ar' => 'محمد تيمور'],
            ['fullname_en' => 'Nidal Al Dibs', 'fullname_ar' => 'نضال الدبس'],
            ['fullname_en' => 'Karim Moussaoui', 'fullname_ar' => 'كريم موسوي'],
        ];


        foreach ($jurors as $juror) {

            Entries::updateOrCreate(['type_id'=>'5','jury_name' => $juror["fullname_en"],'jury_name_arabic' => $juror["fullname_ar"]]);

        }

    }
}
